# Generated by Django 5.1.5 on 2025-03-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0027_emprestimos_email_emprestado_and_more'),
        ('usuarios', '0002_usuario_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={},
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='nome_emprestado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='codigo',
        ),
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='email_emprestado',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livros'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='nome_emprestado_anonimo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.categoria'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='co_autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
