# Generated by Django 5.1.5 on 2025-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0029_alter_livros_options_remove_livros_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
