# Generated by Django 5.1.5 on 2025-03-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0030_livros_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_cadastro',
        ),
    ]
