# Generated by Django 5.1.5 on 2025-03-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0031_remove_livros_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
