# Generated by Django 5.1.5 on 2025-04-22 17:26

import livro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0032_livros_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='data_prevista',
            field=models.DateField(default=livro.models.get_default_data_prevista),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=livro.models.get_default_data_emprestimo),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='nome_emprestado_anonimo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
